# Backend DEV
# Replace {enter-your-GCP-Project-ID} with Google Cloud Platform Project ID

name: omegatrade-backend-dev

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: backend/

jobs:
  build:
    name: Omega Trade Backend Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/qwiklabs-gcp-02-fb2a9647b679/omega-trade/dev/backend:latest -f dockerfile.local.emulator .
          
      - name: Push
        run: |
          docker push gcr.io/qwiklabs-gcp-02-fb2a9647b679/omega-trade/dev/backend:latest
          
      - name: Deploy
        run: |
          gcloud run deploy omegatrade-backend-dev-ga \
          --region us-west1 \
          --image gcr.io/qwiklabs-gcp-02-fb2a9647b679/omega-trade/dev/backend \
          --platform managed \
          --allow-unauthenticated \
          --project qwiklabs-gcp-02-fb2a9647b679 \
          --port 9020 
          
